name: "CI/CD"
on: 
  push:
    branches:
      - main
    tags:
      - '*'
jobs:
  build:
    name: "Build and publish artifacts"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: "Checkout"

      - uses: actions/setup-node@v2
        name: "Setup Node"
      
      - run: npm install
        name: "Install dependencies"

      - run: npm run extract
        name: "Extract lingui"
      
      - run: npm run compile
        name: "Compile lingui"
      
      - run: npm run build
        name: "Build app"

      - run: npm run build:teams
        name: "Build teams package"

      - name: "Upload app artifact"
        uses: actions/upload-artifact@v2
        with:
          name: meeting-break-app
          path: build/
        
      - name: "Upload teams package artifact"
        uses: actions/upload-artifact@v2
        with:
          name: meeting-break-teams-package
          path: meeting-break-teams-package.zip
  deploy:
    name: "Deploy"
    #if: startsWith( github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    env:
      AZURE_WEBAPP_NAME: msteamsmeetingbreak
      AZURE_WEBAPP_PACKAGE_PATH: 'build' 
    steps:
      - uses: actions/checkout@v2
        name: "Checkout"
      
      - name: "Download meeting break app"
        uses: actions/download-artifact@v2
        with:
          name: meeting-break-app

      - name: 'Deploy to Azure'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}